image: maven:3-jdk-8

variables:  
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository

stages: 
  - build
  - test
  - package

maven-build:
  stage: test
  script: 
    - mvn clean package sonar:sonar -Dsonar.host.url=http://sonar.gft.com -Dsonar.jacoco.reportPaths=target/jacoco.exec
compile:    
  stage: build    
  only: [tags]    
  script:        
  - echo Working...    
  tags: [bench-pl-01]