package gft.mentoring;

public enum Family {
    AMS,
    ARCHITECTURE,
    BUSINESS_CONSULTING,
    CORPORATE_SERVICES,
    DATA,
    DIGITAL,
    EXECUTIVE_DIRECTOR,
    PROJECT_DEVELOPMENT,
    PROJECT_GOVERNANCE,
    TESTING;

}
